import '../styles/globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Providers from '@/components/Providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

console.log(process.env.ALCHEMY_API_KEY, process.env.WALLET_CONNECT_PROJECT_ID);

const App = ({ children }: { children: React.ReactNode }) => (
  <Providers>
    <Header />
    {children}
    <Footer />
  </Providers>
);

export default App;
